/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.invoicegenrator;

import java.sql.*;
import javax.swing.*;
import java.io.File;
import java.util.Scanner;
import java.io.FileNotFoundException;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author shubh
 */

public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
  double bheight=0.0;
    /**
     * Creates new form Home
     */
    public Home() {
    initComponents();
    connectDatabase();
    date.setDate(new java.util.Date());
    loadProducts();
  
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        TO = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gst = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        produc = new javax.swing.JTextField();
        qyt = new javax.swing.JTextField();
        dtl = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        addpd = new javax.swing.JButton();
        clr1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        product = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Add Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 440, 48));

        jPanel2.setMinimumSize(new java.awt.Dimension(848, 619));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 620));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Date");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Bill to :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mobile no :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Pin Code :-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Address  :-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        pin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        jPanel2.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 30));

        TO.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        TO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOActionPerformed(evt);
            }
        });
        jPanel2.add(TO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 30));

        num.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        jPanel2.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 280, 30));

        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 280, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("GST");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 110, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Product Name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        gst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "12%", "15%", "30%" }));
        jPanel3.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 110, 30));

        produc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producActionPerformed(evt);
            }
        });
        jPanel3.add(produc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 280, 30));

        qyt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qytActionPerformed(evt);
            }
        });
        jPanel3.add(qyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 70, 30));

        dtl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dtl.setText("delet");
        dtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtlActionPerformed(evt);
            }
        });
        dtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtlKeyPressed(evt);
            }
        });
        jPanel3.add(dtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Price");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 70, 30));

        addpd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addpd.setText("Add Product");
        addpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpdActionPerformed(evt);
            }
        });
        jPanel3.add(addpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        clr1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clr1.setText("Clear");
        clr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr1ActionPerformed(evt);
            }
        });
        clr1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clr1KeyPressed(evt);
            }
        });
        jPanel3.add(clr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 830, 140));

        product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "sr.No", "product name", "Price", "Qyantity", "GST", "Total"
            }
        ));
        jScrollPane2.setViewportView(product);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 830, 200));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 110, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 110, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void TOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void producActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producActionPerformed

    private void qytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qytActionPerformed

    private void dtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtlActionPerformed

    // Get the index of the currently selected row in the JTable
    int selectedRow = product.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product row to delete.", "No Selection", JOptionPane.WARNING_MESSAGE); //error warning 
        return;
    }

    try {
        // 1. Get the Product ID (Sr No) from the selected row.
        // ID is in the first column (index 0)
        Object idObject = product.getModel().getValueAt(selectedRow, 0);
        int productId = -1;
        
        if (idObject instanceof Integer) {
            productId = (Integer) idObject;
        } else {
             productId = Integer.parseInt(idObject.toString());
        }

        // 2. Confirm the deletion with the user
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the selected product (ID: " + productId + ")?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // 3. Delete the record from the database
            String sql = "DELETE FROM products WHERE id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, productId);
            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "🗑️ Product deleted successfully!");
                loadProducts(); // Refresh the JTable
            } else {
                JOptionPane.showMessageDialog(this, "Error: Product not found in database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error parsing Product ID from table: " + e.getMessage(), "Data Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error during deletion: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_dtlActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed
    // TODO add your handling code here:

    private void addpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpdActionPerformed
   String productName = produc.getText();
    String priceText = price.getText();
    String qtyText = qyt.getText();
    String gstValue = gst.getSelectedItem().toString();
    
    if (productName.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all product details!");
        return;
    }
    try {
        double priceValue = Double.parseDouble(priceText);
        int qtyValue = Integer.parseInt(qtyText);

        // 🧮 Extract GST numeric value (remove % and convert to number)
        double gstPercent = Double.parseDouble(gstValue.replace("%", ""));
        
        // 🧮 Calculate total = (price × quantity) + GST%
        double subtotal = priceValue * qtyValue;
        double gstAmount = subtotal * (gstPercent / 100);
        double total = subtotal + gstAmount;

        // 🗃️ Insert into database
        String sql = "INSERT INTO products (PRODUCT_NAME, PRICE, QYNT, GST, TOTAL, DATE) VALUES (?, ?, ?, ?, ?, NOW())";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, productName);
        pst.setDouble(2, priceValue);
        pst.setInt(3, qtyValue);
        pst.setDouble(4, gstPercent);
        pst.setDouble(5, total);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "✅ Product added successfully!"); // msg notification
        loadProducts();

        produc.setText("");
        price.setText("");
        qyt.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number format for price or quantity!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_addpdActionPerformed

    private void dtlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtlKeyPressed
    pin.setText("");
TO.setText("");
num.setText("");
qyt.setText("");
produc.setText("");
price.setText("");    // delete the product selected 
    }//GEN-LAST:event_dtlKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                     
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        bheight = product.getModel().getRowCount(); 

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new BillPrintable(), getPageFormat(pj));
        try {
            if (pj.printDialog()) { // Allow user to select printer/settings
                 pj.print();
                 JOptionPane.showMessageDialog(this, "Invoice sent to printer.", "Print Successful", JOptionPane.INFORMATION_MESSAGE);
                 clearAllFieldsAndData(); // Clear after successful print
            } else {
                 JOptionPane.showMessageDialog(this, "Print job was cancelled.", "Print Cancelled", JOptionPane.WARNING_MESSAGE);
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Error printing invoice: " + ex.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clr1ActionPerformed

    private void clr1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clr1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clr1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearAllFieldsAndData() {
        // 1. Clear customer fields
        TO.setText("");
        num.setText("");
        add.setText("");
        pin.setText("");
        
        // 2. Clear product entry fields
        produc.setText("");
        price.setText("");
        qyt.setText("");
        
        // 3. Truncate the database table
        try {
            // TRUNCATE is faster than DELETE and resets the auto-increment ID (Sr. No.)
            String sql = "TRUNCATE TABLE products";
            PreparedStatement pst = con.prepareStatement(sql);
           pst.executeUpdate();
            
           loadProducts(); // Refresh the table (it will be empty)
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error clearing invoice data: " + e.getMessage());
        }
    }
private void loadProducts() {
    try {
        String sql = "SELECT id, PRODUCT_NAME, PRICE, QYNT, GST, TOTAL FROM products ORDER BY id ASC";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new String[]{ "Sr No", "Product Name", "Price", "Quantity", "GST (%)", "Total (₹)" }, 0
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("PRODUCT_NAME"),
                rs.getDouble("PRICE"),
                rs.getInt("QYNT"),
                rs.getDouble("GST") + "%",
                rs.getDouble("TOTAL")
                     
            });
        }

        product.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "⚠️ Error loading products: " + e.getMessage());
    }

}

public PageFormat getPageFormat(PrinterJob pj){

        PageFormat pf =pj.defaultPage();
        Paper paper = pf.getPaper();
        double bodyHeight = bheight;
        double headerHeight = 5.0;
        double footerHeight = 5.0;
        double width = cm_to_pp(9);
        double height = cm_to_pp(headerHeight+bodyHeight+footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0,10,width,height -cm_to_pp(1));
         
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
    
        return pf;   
}
protected static double cm_to_pp(double cm){
    return toPPI(cm*0.393600787);
}
protected static double toPPI(double inch){
    return inch*72d;
}

public class BillPrintable implements Printable {
    
    // Helper function to calculate the Grand Total from the JTable
    private double calculateGrandTotal() {
        javax.swing.table.TableModel model = product.getModel();
        double grandTotal = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            // The 'Total' column is at index 5
            Object totalObj = model.getValueAt(i, 5);
            if (totalObj instanceof Double) {
                grandTotal += (Double) totalObj;
            }
            // Add other necessary checks for String, etc., if model types vary
        }
        return grandTotal;
    }

    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
            throws PrinterException {
        
        javax.swing.table.TableModel model = product.getModel();
        int r = model.getRowCount(); // Correct row count
        double grandTotal = calculateGrandTotal();

        ImageIcon icon = new ImageIcon("C:\\Users\\shubh\\OneDrive\\Apps\\Documents\\NetBeansProjects\\InvoiceGenrator\\src\\main\\java\\com\\mycompany\\invoicegenrator\\arthublogo.png");
        int result = NO_SUCH_PAGE;
        
        if (pageIndex == 0) {
            Graphics2D g2d = (Graphics2D) graphics;
            //double width = pageFormat.getImageableWidth(); // not strictly needed
            g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());
            
            try {
                int y = 20;
                int yShift = 10;
                int headerRectHeight = 15;
                
                g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                
                // --- Store/Company Info ---
              if (icon.getImage() != null) {
                    g2d.drawImage(icon.getImage() , 50, 20, 90, 30, null);// Use 'null' for image observer
                y += yShift + 30 ;
}
                
                g2d.drawString("------------------------------------------", 12, y); y += yShift;
                g2d.drawString("             ART HUB Creation             ", 12, y); y += yShift;
                g2d.drawString(" 272,Near Dnyaneshwar templ,Dhule,424001  ", 12, y); y += yShift;
           
                g2d.drawString("              www.arthub.com              ", 12, y); y += yShift;
                g2d.drawString("                8698419616                ", 12, y); y += yShift;
                g2d.drawString("------------------------------------------", 12, y); y += headerRectHeight;
                
                // --- Customer Info ---
                g2d.drawString("Bill To: " + TO.getText(), 12, y); y += yShift;
                g2d.drawString("Mobile: " + num.getText(), 12, y); y += yShift;
                g2d.drawString("Date: " + date.getDate().toString(), 12, y); y += yShift;
                g2d.drawString("------------------------------------------", 12, y); y += headerRectHeight;
                
                // --- Table Header ---
                g2d.drawString(" Item Name     Qty  Price  GST(%)   Total", 10, y); y += yShift;
                g2d.drawString("------------------------------------------", 10, y); y += headerRectHeight;
               
        // --- Product Loop with Word Wrapping ---
            for (int s = 0; s < r; s++) {
            String name = model.getValueAt(s, 1).toString();
            String qty = model.getValueAt(s, 3).toString();
            String price = model.getValueAt(s, 2).toString();
            String gst = model.getValueAt(s, 4).toString();
        // Assuming column 5 is always a number or can be formatted as one
        Object totalObj = model.getValueAt(s, 5); 
        String total;
        if (totalObj instanceof Double) {
        total = String.format("%.2f", (Double) totalObj);
        } else {
        // Handle other types if necessary, e.g., if it's a String
        try {
            total = String.format("%.2f", Double.parseDouble(totalObj.toString()));
        } catch (NumberFormatException e) {
            total = "Error";
        }
    }
    int maxNameLength = 15;
    // 1. Get the first line of the item name
    String line1Name = name.length() > maxNameLength ? name.substring(0, maxNameLength) : name;
    // 2. Format the first line with all columns
    String line1 = String.format("%-15s %-4s %-6s %-6s %-6s",
                                 line1Name, qty, price, gst, total);
    g2d.drawString(line1, 10, y);
    y += yShift; // Move down for the next line

    // 3. Check for and draw subsequent wrapped lines
    if (name.length() > maxNameLength) {
        String remainingName = name.substring(maxNameLength);
        
        // Loop through the remaining part, wrapping every 'maxNameLength' characters
        for (int i = 0; i < remainingName.length(); i += maxNameLength) {
            int endIndex = Math.min(i + maxNameLength, remainingName.length());
            String wrappedLineName = remainingName.substring(i, endIndex);
            
            // Draw only the wrapped part of the name, padding to align with the first column.
            // The rest of the columns (Qty, Price, etc.) are left blank on wrapped lines.
            String wrappedLine = String.format("%-15s", wrappedLineName);
            g2d.drawString(wrappedLine, 10, y);
            y += yShift; // Move down for the next line
        }
    }
}

                g2d.drawString("------------------------------------------", 10, y); y += yShift;
                // --- Total Amount ---
                String totalLine = String.format("Total Amt : %30.2f", grandTotal);
                g2d.drawString(totalLine, 10, y); y += yShift;

                g2d.drawString("*******************************************", 10, y); y += yShift;
                g2d.drawString("          Thank You Come Again           ", 10, y); y += yShift;
                g2d.drawString("*******************************************", 10, y); y += yShift;
                g2d.drawString("          Contact - 8698419616            ", 10, y); y += yShift;
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            result = PAGE_EXISTS;
        }
        return result;
    }
}
    /**
     * @param args the command line arguments
     */
    private Connection con;
/**
     * Reads the next invoice number from a local file.
     * @return The next invoice number.
     */
    private int getNextInvoiceNumber() {
        File file = new File("invoice_count.txt");
        if (!file.exists()) {
            return 1; // Start from 1 if the file doesn't exist
        }
        
        try (Scanner scanner = new Scanner(file)) {
            if (scanner.hasNextInt()) {
                return scanner.nextInt();
            }
        } catch (FileNotFoundException e) {
            // This case is handled by the 'return 1' logic
        }
        return 1; // Default to 1 if file is empty or corrupt
    }

    /**
     * Increments the invoice number and saves it back to the file.
     */
private void connectDatabase() {
    try {
        String url = "jdbc:mysql://localhost:3306/sfmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String user = "root";
        String password = "Shubham@1234"; // change if needed

        con=DriverManager.getConnection(url,"root","Shubham@1234");
        System.out.println("✅ Database Connected Successfully!");
        loadProducts(); // Load table at startup
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
    }
}
// Variables declaration - do not modify
    public static void main(String args[]) throws FileNotFoundException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TO;
    private javax.swing.JTextField add;
    private javax.swing.JButton addpd;
    private javax.swing.JButton clr1;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton dtl;
    private javax.swing.JComboBox<String> gst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField num;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField price;
    private javax.swing.JTextField produc;
    private javax.swing.JTable product;
    private javax.swing.JTextField qyt;
    // End of variables declaration//GEN-END:variables
}
